### ISSUE TITLE
Example in documentation

### ISSUE THREAD

**Issue by Potemkinkuliss** [belson17/modred#47]
In 
https://modred.readthedocs.io/en/stable/tutorial_modaldecomp.html
an example for pod decomposition is given. To my understanding the last line
` codes, eig_vals = mr.compute_POD_matrices_snaps_method(
    vecs, list(range(num_modes)))`

should rather read

`modes, eig_vals = mr.compute_POD_arrays_snaps_method(
    vecs, list(range(num_modes)))`

**Comment by jhtu** [comment]
Sorry for the much delayed response.  I believe this is likely due to a mismatch in versions.  The stable version of the docs is older than the latest github repo version.  I am working on a release right now that should fix this.  If you build the documentation locally, it should match the latest interface.
