### ISSUE TITLE
Install error due to Python Version?

### ISSUE THREAD

**Issue by seph-w** [belson17/modred#51]
Hi, 

I'm having issues getting modred installed with Python 3.6.23 (pip version 21.0.1) . 

Package      Version
------------ -------------------
certifi      2020.12.5
numpy        1.19.5
pip          21.0.1
pypi         2.1
setuptools   52.0.0.post20210125
wheel        0.36.2
wincertstore 0.2

The pip install fails. 

**ImportError: modaldecomp requires python version 2.7.x**

If I try the setup.py (from modred-2.0.4.post6) it fails with an error 

**TypeError: 'version' object is not iterable**

Do I have anything wrong with my environment configuration? 

Thanks

**Comment by jhtu** [comment]
This was a bug that we have fixed in the source code, but unfortunately we have not published the release yet.  (We hope to soon!)

You can resolve this by downloading the source code from github and running `python setup.py install` from the code directory.  I believe there is a pip command to install from a github URL too, if you want to do that instead.  Something like this `pip install git+https://github.com/belson17/modred`.

**Comment by moritz1778** [comment]
Hello,

I have the exact same error and wanted to ask if there is any solution to it?

the python setup.py install also fails unfortunately?

best regards!

**Comment by jhtu** [comment]
Did you try the setup.py from the github repo, not the PyPI package?

**Comment by jhtu** [comment]
I just released a new version of the code, so it should install fine from PyPI.  The new version is 2.1.0 and has many new features.  Sorry for the slow response.  I hope you are still using the code, and if so, I am happy to try and help you resolve any issues you have.
