### ISSUE TITLE
Check that type checks in InnerProductTrapz catch non numpy arrays

### ISSUE THREAD

**Issue by belson17** [belson17/modred#9]
In emails from Milos, it looked like our type check that the arguments to **call** are numpy arrays didn't work as expected.

**Comment by jhtu** [comment]
Just took a look at this function and I don't even think it works, aside from this type check.  If you look at the inner_product() function, it first defines the value of IP, then loops through grids, each time assigning a new value to IP.  I would expect maybe a =+ rather than a reassignment.  Right now the IP is calculated once per grid, and then only the value for the last (of the reversed grid list) is returned.

**Comment by jhtu** [comment]
Function does actually work.  @belson17 added a more detailed comment to explain what it does.  Unclear what original issue refers to, since there are no type checks remaining in this function, so closing the issue.
